version: "3.8"

networks:
  fe-i-prod:

services:
  nginx_frontend_prod:
    image: nginx:stable
    container_name: fe_nginx_prod
    restart: unless-stopped
    ports:
      - "8001:80"
    links:
      - frontend_prod
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site-prod.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - frontend_prod
    networks:
      - fe-i-prod
  frontend_prod:
    build:
      context: .
      dockerfile: DockerFile
    container_name: fe_prod
    env_file: ./.env
    volumes:
      - ./.env:/app/.env:rw
    networks:
      - fe-i-prod
